<?php

	HeadScript('added_css', 'pins.css');

?>

<div class="container-pins">
	<?php foreach($this->users as $id => $user): ?>
		<div class="pin" style="width: 100%;">
			<div>
				<center>
					<p class="pin-caption">
						<b><?= $user; ?></b>
					</p>
				</center>
				<div class="pin-bottom">
					<?php if (Model_User::getId() != $id): ?>
						<a href="<?= $this->url(array('controller' => 'profile', 'action' => 'switch', 'id' => $id), 'default', true); ?>" class="btn btn-primary pull-left">Swith to user</a>
						<?php if (in_array($id, $this->consumers)): ?>
							<a href="<?= $this->url(array('controller' => 'profile', 'action' => 'unfollow', 'id' => $id), 'default', true); ?>" class="btn btn-danger">Unfollow</a>
						<?php else: ?>
							<a href="<?= $this->url(array('controller' => 'profile', 'action' => 'follow', 'id' => $id), 'default', true); ?>" class="btn btn-success">Follow</a>
						<?php endif; ?>
					<?php endif; ?>
				</div>
			</div>
		</div>
	<?php endforeach; ?>
</div>