<?php

HeadScript('default_css');
HeadScript('default_js');

$js = $js_base = '';
if (APPLICATION_ENV == 'development')
	$js_base .= 'window._env = "'.APPLICATION_ENV.'";';

if (config('domain'))
	$js_base .= 'window.domain = "'.config('domain').'";';

?>

<?= $this->doctype(); //doctype is defined in Bootstrap::_initViewHelpers() (in application/Bootstrap.php file) ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		-combiner_css-
		<?php if (!empty($js_base)): ?>
			<script type="text/javascript" charset="utf-8"><?= $js_base; ?></script>
		<?php endif; ?>
		-combiner_js-
		<script type="text/javascript" charset="utf-8">@simplejs</script>
		-onDomReady-
	</head>
	<body>
		<div class="container">
			<?= $this->layout()->render('header'); ?>
			<div class="user-container well well-small">
				<b>Current User: <?= Model_User::getName(Model_User::getId()); ?></b>
				<?php $notification_count = Model_Pin_Manager::getInstance()->getFeedByType(Model_User::getId(), 'notification')->getDenormalizedCount(); ?>
				<?php if ($notification_count > 0): ?>
					<div class="pull-right">
						Unseen Notifications: <a href="<?= $this->url(array('controller' => 'feed', 'action' => 'notification'), 'default', true); ?>" class="badge badge-important">
							<?= $notification_count; ?>
						</a>
					</div>
				<?php endif; ?>
			</div>
			<div class="content">
				<?= $this->layout()->content; ?>
			</div>
			<?= $this->layout()->render('footer'); ?>
		</div>
	</body>
</html>

<?php
	Gp_FinalReplacer::getInstance()->set('simplejs','.='.$js);
?>