<?php

	HeadScript('added_css', 'pins.css');

?>

<?php foreach($this->activities as $activity): ?>
	<div class="well flat">
		<a href="<?= $this->url(array('controller' => 'profile', 'action' => $activity->get('actor_id')), 'default', true); ?>">
			<?= Model_User::getName($activity->get('actor_id')); ?>
		</a>
		<?= $activity->get('verb')->past_tense; ?> picture<br />
		<small><?= /*$this->utils()->ago(*/date('H:i:s d.m.Y', $activity->get('time') / 1000); ?></small>
		<center>
			<img src="/<?= $this->items[$activity->get('extra_context')['item_id']]['url']; ?>" />
		</center>
	</div>
<?php endforeach;