<?php

HeadScript('default_css');
HeadScript('default_js');

$js = $js_base = '';
if (APPLICATION_ENV == 'development')
	$js_base .= 'window._env = "'.APPLICATION_ENV.'";';

if (config('domain'))
	$js_base .= 'window.domain = "'.config('domain').'";';

?>

<?= $this->doctype(); //doctype is defined in Bootstrap::_initViewHelpers() (in application/Bootstrap.php file) ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		-combiner_css-
		<?php if (!empty($js_base)): ?>
			<script type="text/javascript" charset="utf-8"><?= $js_base; ?></script>
		<?php endif; ?>
		-combiner_js-
		<script type="text/javascript" charset="utf-8">@simplejs</script>
		-onDomReady-
	</head>
	<body>
		Default Layout <br />
		<?= $this->layout()->render('header'); ?>
		<?= $this->layout()->content; ?>
		<?= $this->layout()->render('footer'); ?>
	</body>
</html>

<?php
	Gp_FinalReplacer::getInstance()->set('simplejs','.='.$js);
?>